### PR TITLE
Experiment 2

### PR DESCRIPTION
**Pull request by cvitolo**
Paths amended according to current content of the ewc data instance

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-projects/ai-vegetation-fuel?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-projects/ai-vegetation-fuel?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-projects/ai-vegetation-fuel?pullRequest=9) it.</sub>

**Comment by cvitolo** [comment]
To do: the new notebooks have some additional dependecies. For reproducibility, requirements and dockerfile need to be updated!

**Review by fdg10371 — APPROVED** [review]
I think is ok

**Comment by fdg10371** [comment]
I think is fine

**Comment by cvitolo** [comment]
@fdg10371 could you please have a second look?

**Comment by fdg10371** [comment]
well done!

**Pull request merged**
